mqtt:
  broker:
    url: tcp://localhost:1883
    username: admin
    password: 1234
  topics:
    filename: topics.txt
logging:
  file:
    name: logs/application.log
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: sensor_data